langchain4j:
  open-ai:
    chat-model:
      base-url:  https://api.deepseek.com
      api-key:  sk-4654b23fdd8642678de04a877a6efb9d
      model-name:  deepseek-chat
      log-requests:  true
      log-responses: true
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
    streaming-chat-model:
      base-url:  https://api.deepseek.com
      api-key:  sk-4654b23fdd8642678de04a877a6efb9d
      model-name:  deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      #流式输出不能直接结构化输出，所以不能使用strict-json-schema
