spring:
  application:
    name: get-ai-code-mother
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 200429
    url: jdbc:mysql://localhost:3306/get_ai_code_mother
  profiles:
    active: local
  lifecycle:
    timeout-per-shutdown-phase: 60s
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 3600
      password:
  #session配置
  session:
    store-type: redis
    timeout: 259200

server:
  port: 8123
  servlet:
    context-path: /api


# springdoc-openapi????
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.getian.getaicodemother.controller
knife4j:
  enable: true   #启动Knife4j的增强工具
  setting:
    language: zh_cn  #页面设置为中文


